# Generated by Django 3.2.3 on 2021-06-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttmce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='htmls',
            new_name='content',
        ),
    ]
