# Generated by Django 3.2.3 on 2021-06-25 10:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttmce', '0002_rename_htmls_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='contentMCE',
        ),
        migrations.AddField(
            model_name='message',
            name='contentCKE',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
