# Generated by Django 3.2.3 on 2021-06-25 10:35

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ttmce', '0003_auto_20210625_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuillPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='contentQLL',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
